package com.ours.tester;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class Utils {

	public static final float DELAY_LIMIT_TOBE_COUNTED = 0.3f;

	public static void FileWrite(String file_location, String data,
			boolean appendable) {

		try {
			FileWriter fw = new FileWriter(file_location, appendable);
			fw.write(data);
			fw.close();
		} catch (IOException e) {
			System.out.println("exception happened - here's what I know: ");
			e.printStackTrace();

		}
	}

	public String getUnixKernelTimeStamp(String dmesg_string, String pattern) {

		Pattern pTime = Pattern.compile("\\[\\s*(\\d*.\\d\\d\\d\\d\\d\\d)\\].*"
				+ pattern);
		Matcher mTime = pTime.matcher(dmesg_string);

		String time = null;
		if (mTime.find()) {
			// System.out.println("Time " + mTime.group(1));
			time = mTime.group(1);
		}
		return time;
	}

	public String convertgetEventToSendEvent(String getevent_file_location)
			throws IOException {

		BufferedReader br = new BufferedReader(new FileReader(
				getevent_file_location));
		StringBuilder sb = new StringBuilder("#!/bin/sh\n");
		sb.append("#This is generated by myTester adb event injection util");
		sb.append(System.lineSeparator());
		String t = "0.0";
		String tNext = "0.0";
		Float delay = null;
		try {
			String line = br.readLine();
			int l = 1;
			while (line != null) {

				if (line.startsWith("[")) {

					String device = line.split(":")[0].split("]")[1].trim();
					String events = line.split(":")[1];
					String eventCmd = "";
					// System.out.println(line);
					tNext = getUnixKernelTimeStamp(line, "/dev/input/");
					// System.out.println(tNext);
					for (int i = 1; i < 4; i++) {
						String hexNum = events.split(" ")[i].trim();
						String evt;
						try {
							int n = Integer.parseInt(hexNum, 16);
							evt = String.valueOf(n);
						} catch (NumberFormatException e) {
							long n1 = Long.valueOf(hexNum, 16).longValue();
							evt = String.valueOf(n1);
						}
						eventCmd = eventCmd + " " + evt;
					}
					if (l != 1) {
						delay = Float.parseFloat(tNext) - Float.parseFloat(t);
						// System.out.println("delay " + delay);
					}
					t = tNext;
					String adb_cmd = "sendevent " + device.trim() + " "
							+ eventCmd;
					// System.out.println(adb_cmd);
					sb.append(adb_cmd);

					if ((l != 1) && (delay > DELAY_LIMIT_TOBE_COUNTED)) {
						sb.append(System.lineSeparator());
						sb.append("sleep " + delay + ";");
						sb.append(System.lineSeparator());
					}
					sb.append(System.lineSeparator());
					l++;
				}

				line = br.readLine();

			}

		} catch (IOException e) {
			System.out.println("exception happened - here's what I know: ");
			e.printStackTrace();

		} finally {
			br.close();
		}
		String mes_script_file = getevent_file_location.replace("mel", "mes");
		FileWrite(mes_script_file, sb.toString(), false);
		return mes_script_file;
	}
}
